feat: notification
PrayHelper/uspray-spring pull request #127
Opened 2024-01-16 18:37 UTC by Sion99

## ✅ PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 변경
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 📌 관련 이슈

## ✨ 과제 내용

- 이슈 #118 에 맞게 알림 기능을 추가합니다.
- 사용자의 알림 설정 조회하는 api를 추가하였습니다.
- group 알림 설정을 추가하였습니다.

일단 동작만 하도록 추가하였고, 추후 group과 grouppray에 필요한 알림을 넣으면 좋을 것 같습니다.

## 📸 스크린샷(선택)

## 📚 레퍼런스 (또는 새로 알게 된 내용) 혹은 궁금한 사항들

2024-01-16 19:01 UTC, baebae02 requested changes
손목 부상에 고생이 많으십니다. 🥲🥲 화이팅입니다 !!

2024-01-16 19:01 UTC, baebae02 commented on src/main/java/com/uspray/uspray/controller/MemberController.java
>      public ApiResponseDto<?> setNotificationAgree(
prayTimeNoti, prayForMeNoti, SharedNoti, GroupNoti에 맞게 
NotificationAgreeDto 속 NotificationType을 int가 아닌 Type으로 관리하면 좋을 것 같은데 혹시 어떻게 생각하시는 지 궁금합니다!

2024-01-16 19:31 UTC, Sion99 commented on src/main/java/com/uspray/uspray/controller/MemberController.java
>      public ApiResponseDto<?> setNotificationAgree(
NotificationAgreeDto의 NotificationType은 int가 아니긴합니다만, NOTI_TYPE 이런식으로 String 값이 Enum으로 바로 전환되는 걸 말하시는 건가요?

2024-01-17 21:33 UTC, baebae02 commented on src/main/java/com/uspray/uspray/domain/Member.java
> +    private Boolean fourthNotiAgree = true;
음 다시 생각해보니 나중에 알림 내용이 바뀔 경우 변수 명을 모두 바꿔야 하는 불상사가 생길 것 같아 그냥 원래대로 냅두겠습니다 !

2024-01-17 21:36 UTC, merged