fix: category update 에러 수정
PrayHelper/uspray-spring pull request #158
Opened 2024-03-21 17:24 UTC by baebae02

## ✅ PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [ ] 기능 추가
- [ ] 기능 변경
- [ ] 기능 삭제
- [X] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 📌 관련 이슈
59. put /category -> 색깔만 수정하면 오류가 나요, 이름을 수정해야 200이 와요

## ✨ 과제 내용

## 📸 스크린샷(선택)

## 📚 레퍼런스 (또는 새로 알게 된 내용) 혹은 궁금한 사항들

2024-03-22 01:28 UTC, dong2ast requested changes
고생하셨습니다~~ 리뷰 확인하고 다시 말씀 주세요 👍

2024-03-22 01:28 UTC, dong2ast commented on src/main/java/com/uspray/uspray/service/GroupService.java
> +            groupId, targetname);
username을 repository 단으로 내려보내서 querydsl에서 select할 당시에 username을 제외한 데이터를 기져오도록 하는 것은 어떨까요?

2024-03-22 01:28 UTC, dong2ast commented on src/main/java/com/uspray/uspray/service/GroupService.java
> +            }
else 예약어를 사용하지 않는 편이 좋지만, 이 부분도 위 방식이 적용된다면 사라지긴 하네요 :)

2024-03-22 03:16 UTC, Sion99 commented on src/main/java/com/uspray/uspray/service/CategoryService.java
> +        if (categoryRequestDto.getName() != null) {
오류가 null 가드 안해서 발생한 건가요?

2024-03-22 13:10 UTC, dong2ast approved these changes

2024-03-22 18:25 UTC, baebae02 commented on src/main/java/com/uspray/uspray/service/GroupService.java
> +            groupId, targetname);
오 repository단에서 데이터에 대한 필터링을 마친 후 Service 단에서는 가공만 하라는 것이군요. 그게 더 좋을 것 같습니다. 수정하겠습니다

2024-03-22 18:26 UTC, baebae02 commented on src/main/java/com/uspray/uspray/service/CategoryService.java
> +        if (categoryRequestDto.getName() != null) {
넵! category getName이 없는 Dto도 있는데 그 Dto에 getName 을 CheckDuplicate 해서 에러가 났었습니다 :)

2024-03-23 00:41 UTC, Sion99 approved these changes

2024-03-24 05:04 UTC, merged