feat: member fcm token update API
PrayHelper/uspray-spring pull request #166
Opened 2024-04-04 20:28 UTC by baebae02

## ✅ PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [X] 기능 추가
- [ ] 기능 변경
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 📌 관련 이슈
６８。 디바이스 토큰만 ｄａｔａ로 담아서 보내면
ｊｗｔ 토큰 주인의 디바이스토큰 ｆｉｒｅｂａｓｅＴｏｋｅｎ 값이 ｕｐｄａｔｅ 되는 ａｐｉ가 필요합니다、、、¡ ［ＰＯＳＴ］

## ✨ 과제 내용
memberController에 jwt token update 하는 API를 추가하였습니다.

## 📸 스크린샷(선택)

## 📚 레퍼런스 (또는 새로 알게 된 내용) 혹은 궁금한 사항들

2024-04-05 04:36 UTC, dong2ast requested changes

2024-04-05 04:36 UTC, dong2ast commented on src/main/java/com/uspray/uspray/InitDb.java
혹시 이거 InitDb 설정해둔거 의도된 것인지 한번 확인 해줄 수 있나요?

2024-04-05 04:51 UTC, baebae02 commented on src/main/java/com/uspray/uspray/InitDb.java
엇 뭐야 분명 git add에서 제외했는데 제가 실수했나봅니다. 다시 수정사항 뺴도록 하겠습니다 확인 감사합니다!

2024-04-06 10:00 UTC, dong2ast approved these changes
확인했습니다 고생하셨습니다~~👍👍

2024-04-08 02:18 UTC, merged