Feat/#4 create member entity
PrayHelper/uspray-spring pull request #5
Opened 2023-09-12 12:44 UTC by dong2ast

## ✅ PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [ ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 📌 관련 이슈

closed #4 

## ✨ 과제 내용

* Member 엔티티 생성
* 객체의 생성일 및 최종 수정일을 알기 위한 객체 생성

## 📸 스크린샷(선택)

## 📚 레퍼런스 (또는 새로 알게 된 내용) 혹은 궁금한 사항들

2023-09-12 14:26 UTC, Sion99 approved these changes
수고하셨습니다 👍

2023-09-13 08:41 UTC, baebae02 requested changes
지금 build 하면 에러 나네요 ! gradle에` runtimeOnly("org.postgresql:postgresql")` 추가해주세요 ~

2023-09-13 14:22 UTC, baebae02 commented
> > 지금 build 하면 에러 나네요 ! gradle에` runtimeOnly("org.postgresql:postgresql")` 추가해주세요 ~
> 
> 해당 라이브러리 관한 내용은 이전 Pr에 추가 되어있습니다! 확인 되시면 approve 해주세요~

아하 어쩐지 ... 걘 돌아가고 얜 안돌아갔군요 죄송합니다 approve 후 머지할게요 ~

2023-09-13 14:22 UTC, baebae02 approved these changes

2023-09-13 14:22 UTC, merged